services:
  webclient:
    build:
      dockerfile: Dockerfile.webclient
      context: .
      args:
        https_proxy: http://127.0.0.1:8889
      network: host
    image: ghcr.io/mshatoori/goatak-client:latest
#    ports:
#      - "8080:8080"
#      - "6969"
    environment:
      - ME_UID=${ME_UID}
      - CALLSIGN=${CALLSIGN}
      - MAP_SERVER=127.0.0.1:8000
      - GPSD=127.0.0.1:2948
    network_mode: host
  map:
    # build:
    #   dockerfile: ./Dockerfile
    #   context: ./maps
    image: ghcr.io/mshatoori/goatak-maps:latest
    ports:
      - "8000:8000"
  gpsd:
    image: ghcr.io/mshatoori/docker-gpsd:latest
    ports:
      - "2948:2947"
      - "5577:5577/udp"
    command:
      - "-D2"
      - "udp://0.0.0.0:5577"
  server:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        https_proxy: http://127.0.0.1:8889
      network: host
    ports:
      - "8087:8080"
      - "8089:8088"