FROM registry.docker.ir/maptiler/tileserver-gl:v5.4.0

COPY contents/merged.pmtiles /data/contents/merged.pmtiles
COPY contents/glyphs/ /data/contents/glyphs/
COPY contents/sprites/ /data/contents/sprites/
COPY style.json /data/style.json
COPY config.json /data/config.json