services:
  webclient2:
    build:
      dockerfile: Dockerfile.webclient
      context: ..
    #      network: host
    #    pull_policy: always
    image: ghcr.io/mshatoori/goatak-client:latest
    ports:
      - "8082:8080"
      - "6971:6969"
      - "6971:6969/udp"
    volumes:
      - .:/workspace:cached
      - ./goatak_client-7.yml:/app/goatak_client.yml
    networks:
      - mmhs
  map:
    #    build:
    #      context: ../maps
    #      dockerfile: ../maps/Dockerfile
    image: ghcr.io/mshatoori/goatak-maps:latest
    ports:
      - "8000:8000"
    networks:
      - mmhs
  gpsd:
    image: ghcr.io/mshatoori/docker-gpsd:latest
    ports:
      - "2947:2947"
      - "5577:5577/udp"
    command:
      - "-D2"
      - "udp://0.0.0.0:5577"
    networks:
      - mmhs

networks:
  mmhs:
    name: mmhs-network
    external: true
